about: |
  AutoML API Java Client is now available in the new Vertex AI.
  Migrate your AutoML resources to Vertex AI to get the latest features
  like data labeling, AutoML-powered training, and endpoint management. 

  [Migrate to Vertex AI documentation](https://cloud.google.com/vertex-ai/docs/start/migrating-to-vertex-ai)

  [Cloud Auto ML](https://cloud.google.com/automl/docs/) makes the power 
  of machine learning available to you even if you have limited knowledge 
  of machine learning. You can use AutoML to build on Google's machine 
  learning capabilities to create your own custom machine learning models 
  that are tailored to your business needs, and then integrate those 
  models into your applications and web sites.

  See the [Cloud Auto ML client library docs](https://cloud.google.com/java/docs/reference/google-cloud-automl/latest/history)
  to learn how to use this Cloud Auto ML Client Library.
