// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/automl/v1/text.proto

package com.google.cloud.automl.v1;

public final class TextProto {
  private TextProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_automl_v1_TextClassificationDatasetMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_automl_v1_TextClassificationDatasetMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_automl_v1_TextClassificationModelMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_automl_v1_TextClassificationModelMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_automl_v1_TextExtractionDatasetMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_automl_v1_TextExtractionDatasetMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_automl_v1_TextExtractionModelMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_automl_v1_TextExtractionModelMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_automl_v1_TextSentimentDatasetMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_automl_v1_TextSentimentDatasetMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_automl_v1_TextSentimentModelMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_automl_v1_TextSentimentModelMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!google/cloud/automl/v1/text.proto\022\026goo" +
      "gle.cloud.automl.v1\032\037google/api/field_be" +
      "havior.proto\032+google/cloud/automl/v1/cla" +
      "ssification.proto\032\034google/api/annotation" +
      "s.proto\"l\n!TextClassificationDatasetMeta" +
      "data\022G\n\023classification_type\030\001 \001(\0162*.goog" +
      "le.cloud.automl.v1.ClassificationType\"j\n" +
      "\037TextClassificationModelMetadata\022G\n\023clas" +
      "sification_type\030\003 \001(\0162*.google.cloud.aut" +
      "oml.v1.ClassificationType\"\037\n\035TextExtract" +
      "ionDatasetMetadata\"\035\n\033TextExtractionMode" +
      "lMetadata\"5\n\034TextSentimentDatasetMetadat" +
      "a\022\025\n\rsentiment_max\030\001 \001(\005\"\034\n\032TextSentimen" +
      "tModelMetadataB\265\001\n\032com.google.cloud.auto" +
      "ml.v1B\tTextProtoP\001Z<google.golang.org/ge" +
      "nproto/googleapis/cloud/automl/v1;automl" +
      "\252\002\026Google.Cloud.AutoML.V1\312\002\026Google\\Cloud" +
      "\\AutoMl\\V1\352\002\031Google::Cloud::AutoML::V1b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.cloud.automl.v1.ClassificationProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_cloud_automl_v1_TextClassificationDatasetMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_automl_v1_TextClassificationDatasetMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_automl_v1_TextClassificationDatasetMetadata_descriptor,
        new java.lang.String[] { "ClassificationType", });
    internal_static_google_cloud_automl_v1_TextClassificationModelMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_automl_v1_TextClassificationModelMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_automl_v1_TextClassificationModelMetadata_descriptor,
        new java.lang.String[] { "ClassificationType", });
    internal_static_google_cloud_automl_v1_TextExtractionDatasetMetadata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_automl_v1_TextExtractionDatasetMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_automl_v1_TextExtractionDatasetMetadata_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_automl_v1_TextExtractionModelMetadata_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_automl_v1_TextExtractionModelMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_automl_v1_TextExtractionModelMetadata_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_automl_v1_TextSentimentDatasetMetadata_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_automl_v1_TextSentimentDatasetMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_automl_v1_TextSentimentDatasetMetadata_descriptor,
        new java.lang.String[] { "SentimentMax", });
    internal_static_google_cloud_automl_v1_TextSentimentModelMetadata_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_automl_v1_TextSentimentModelMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_automl_v1_TextSentimentModelMetadata_descriptor,
        new java.lang.String[] { });
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.cloud.automl.v1.ClassificationProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
